[2023-04-13T12:12:07.872+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.inject_data manual__2023-04-13T12:12:01.519007+00:00 [queued]>
[2023-04-13T12:12:07.883+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.inject_data manual__2023-04-13T12:12:01.519007+00:00 [queued]>
[2023-04-13T12:12:07.885+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:12:07.886+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T12:12:07.888+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:12:07.901+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): inject_data> on 2023-04-13 12:12:01.519007+00:00
[2023-04-13T12:12:07.907+0000] {standard_task_runner.py:55} INFO - Started process 736 to run task
[2023-04-13T12:12:07.911+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'inject_data', 'manual__2023-04-13T12:12:01.519007+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpr9qaccxk']
[2023-04-13T12:12:07.913+0000] {standard_task_runner.py:83} INFO - Job 153: Subtask inject_data
[2023-04-13T12:12:07.978+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.inject_data manual__2023-04-13T12:12:01.519007+00:00 [running]> on host ffea11fb791c
[2023-04-13T12:12:08.076+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=inject_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T12:12:01.519007+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T12:12:01.519007+00:00
[2023-04-13T12:12:08.078+0000] {sql.py:254} INFO - Executing: 
        INSERT INTO measures_ext (timestamp, temp, humidity, cloudiness, wind_speed) VALUES
        (1681387840,
        287.4),
        48),
        clear sky),
        2.28);
        
[2023-04-13T12:12:08.087+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T12:12:08.262+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T12:12:08.267+0000] {sql.py:375} INFO - Running statement: 
        INSERT INTO measures_ext (timestamp, temp, humidity, cloudiness, wind_speed) VALUES
        (1681387840,
        287.4),
        48),
        clear sky),
        2.28);
        , parameters: None
[2023-04-13T12:12:08.268+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: near "48": syntax error
[2023-04-13T12:12:08.278+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=inject_data, execution_date=20230413T121201, start_date=20230413T121207, end_date=20230413T121208
[2023-04-13T12:12:08.289+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 153 for task inject_data (near "48": syntax error; 736)
[2023-04-13T12:12:08.333+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T12:12:08.350+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
