[2023-04-13T08:26:03.232+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_data manual__2023-04-13T08:26:01.183937+00:00 [queued]>
[2023-04-13T08:26:03.263+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_data manual__2023-04-13T08:26:01.183937+00:00 [queued]>
[2023-04-13T08:26:03.266+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T08:26:03.269+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T08:26:03.274+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T08:26:03.313+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): transform_data> on 2023-04-13 08:26:01.183937+00:00
[2023-04-13T08:26:03.327+0000] {standard_task_runner.py:55} INFO - Started process 2150 to run task
[2023-04-13T08:26:03.348+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'transform_data', 'manual__2023-04-13T08:26:01.183937+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp89fnhj7m']
[2023-04-13T08:26:03.353+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask transform_data
[2023-04-13T08:26:03.542+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.transform_data manual__2023-04-13T08:26:01.183937+00:00 [running]> on host 0607b07c4f39
[2023-04-13T08:26:03.656+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T08:26:01.183937+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T08:26:01.183937+00:00
[2023-04-13T08:26:03.694+0000] {logging_mixin.py:137} INFO - None
[2023-04-13T08:26:03.698+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_dag.py", line 19, in transform_data
    timestamp = info["dt"]
TypeError: 'NoneType' object is not subscriptable
[2023-04-13T08:26:03.733+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=transform_data, execution_date=20230413T082601, start_date=20230413T082603, end_date=20230413T082603
[2023-04-13T08:26:03.775+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 38 for task transform_data ('NoneType' object is not subscriptable; 2150)
[2023-04-13T08:26:03.801+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T08:26:03.836+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
