[2023-04-13T12:10:42.380+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_data manual__2023-04-13T12:10:37.535897+00:00 [queued]>
[2023-04-13T12:10:42.394+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_data manual__2023-04-13T12:10:37.535897+00:00 [queued]>
[2023-04-13T12:10:42.395+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:10:42.396+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T12:10:42.398+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T12:10:42.413+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): transform_data> on 2023-04-13 12:10:37.535897+00:00
[2023-04-13T12:10:42.420+0000] {standard_task_runner.py:55} INFO - Started process 692 to run task
[2023-04-13T12:10:42.424+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'transform_data', 'manual__2023-04-13T12:10:37.535897+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpkuuusjg8']
[2023-04-13T12:10:42.426+0000] {standard_task_runner.py:83} INFO - Job 149: Subtask transform_data
[2023-04-13T12:10:42.497+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.transform_data manual__2023-04-13T12:10:37.535897+00:00 [running]> on host ffea11fb791c
[2023-04-13T12:10:42.566+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T12:10:37.535897+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T12:10:37.535897+00:00
[2023-04-13T12:10:42.569+0000] {logging_mixin.py:137} INFO - <TaskInstance: weather_dag.transform_data manual__2023-04-13T12:10:37.535897+00:00 [running]>
[2023-04-13T12:10:42.585+0000] {logging_mixin.py:137} INFO - {'coord': {'lon': 24.0232, 'lat': 49.8383}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 287.4, 'feels_like': 286.13, 'temp_min': 287.4, 'temp_max': 287.4, 'pressure': 1006, 'humidity': 48, 'sea_level': 1006, 'grnd_level': 973}, 'visibility': 10000, 'wind': {'speed': 2.28, 'deg': 266, 'gust': 2.81}, 'clouds': {'all': 7}, 'dt': 1681387840, 'sys': {'country': 'UA', 'sunrise': 1681356971, 'sunset': 1681405948}, 'timezone': 10800, 'id': 702550, 'name': 'Lviv', 'cod': 200}
[2023-04-13T12:10:42.587+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_dag.py", line 23, in transforming_data
    cloudiness = info["weather"]["description"]
TypeError: list indices must be integers or slices, not str
[2023-04-13T12:10:42.599+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=transform_data, execution_date=20230413T121037, start_date=20230413T121042, end_date=20230413T121042
[2023-04-13T12:10:42.611+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 149 for task transform_data (list indices must be integers or slices, not str; 692)
[2023-04-13T12:10:42.640+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T12:10:42.667+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
