[2023-04-14T15:33:26.877+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.choose_endpoint_Zhmerynka scheduled__2023-04-14T14:00:00+00:00 [queued]>
[2023-04-14T15:33:26.933+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.choose_endpoint_Zhmerynka scheduled__2023-04-14T14:00:00+00:00 [queued]>
[2023-04-14T15:33:26.936+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T15:33:26.942+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-14T15:33:26.947+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T15:33:27.073+0000] {taskinstance.py:1309} INFO - Executing <Task(BranchPythonOperator): choose_endpoint_Zhmerynka> on 2023-04-14 14:00:00+00:00
[2023-04-14T15:33:27.117+0000] {standard_task_runner.py:55} INFO - Started process 14948 to run task
[2023-04-14T15:33:27.177+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'choose_endpoint_Zhmerynka', 'scheduled__2023-04-14T14:00:00+00:00', '--job-id', '516', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpzfwf6myp']
[2023-04-14T15:33:27.219+0000] {standard_task_runner.py:83} INFO - Job 516: Subtask choose_endpoint_Zhmerynka
[2023-04-14T15:33:27.636+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.choose_endpoint_Zhmerynka scheduled__2023-04-14T14:00:00+00:00 [running]> on host ffea11fb791c
[2023-04-14T15:33:27.888+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=choose_endpoint_Zhmerynka
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T14:00:00+00:00
[2023-04-14T15:33:27.892+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 210, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: choosing_endpoint() missing 1 required positional argument: 'city'
[2023-04-14T15:33:27.908+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=choose_endpoint_Zhmerynka, execution_date=20230414T140000, start_date=20230414T153326, end_date=20230414T153327
[2023-04-14T15:33:27.962+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 516 for task choose_endpoint_Zhmerynka (choosing_endpoint() missing 1 required positional argument: 'city'; 14948)
[2023-04-14T15:33:28.013+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T15:33:28.099+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
