[2023-04-12T05:48:45.482+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2023-04-12T05:48:43.855000+00:00 [queued]>
[2023-04-12T05:48:45.508+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2023-04-12T05:48:43.855000+00:00 [queued]>
[2023-04-12T05:48:45.515+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T05:48:45.518+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-12T05:48:45.519+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T05:48:45.541+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-12 05:48:43.855000+00:00
[2023-04-12T05:48:45.551+0000] {standard_task_runner.py:55} INFO - Started process 981 to run task
[2023-04-12T05:48:45.558+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'create_table', 'manual__2023-04-12T05:48:43.855000+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpwwo7tpcj']
[2023-04-12T05:48:45.563+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask create_table
[2023-04-12T05:48:45.736+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.create_table manual__2023-04-12T05:48:43.855000+00:00 [running]> on host 0607b07c4f39
[2023-04-12T05:48:45.891+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T05:48:43.855000+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T05:48:43.855000+00:00
[2023-04-12T05:48:45.897+0000] {sql.py:254} INFO - Executing: CREATE TABLE IF NOT EXISTS ...
[2023-04-12T05:48:46.162+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgresql://nazar:1111@localhost:5432/uku/***-pipilines` isn't defined
[2023-04-12T05:48:46.176+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=create_table, execution_date=20230412T054843, start_date=20230412T054845, end_date=20230412T054846
[2023-04-12T05:48:46.204+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task create_table (The conn_id `postgresql://nazar:1111@localhost:5432/uku/***-pipilines` isn't defined; 981)
[2023-04-12T05:48:46.248+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T05:48:46.287+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
