[2023-04-13T11:35:27.573+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2023-04-13T11:35:26.426543+00:00 [queued]>
[2023-04-13T11:35:27.592+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2023-04-13T11:35:26.426543+00:00 [queued]>
[2023-04-13T11:35:27.594+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T11:35:27.596+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T11:35:27.598+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T11:35:27.622+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): create_table> on 2023-04-13 11:35:26.426543+00:00
[2023-04-13T11:35:27.630+0000] {standard_task_runner.py:55} INFO - Started process 3150 to run task
[2023-04-13T11:35:27.633+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'create_table', 'manual__2023-04-13T11:35:26.426543+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp7szi27j6']
[2023-04-13T11:35:27.635+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask create_table
[2023-04-13T11:35:27.735+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.create_table manual__2023-04-13T11:35:26.426543+00:00 [running]> on host 0607b07c4f39
[2023-04-13T11:35:27.813+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T11:35:26.426543+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T11:35:26.426543+00:00
[2023-04-13T11:35:27.816+0000] {sql.py:254} INFO - Executing: CREATE TABLE IF NOT EXISTS measures (
                                         timestamp TIMESTAMP NOT NULL,
                                         temp FLOAT
                                        );
[2023-04-13T11:35:27.827+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T11:35:28.006+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T11:35:28.009+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/sqlite/hooks/sqlite.py", line 38, in get_conn
    conn = sqlite3.connect(airflow_conn.host)
sqlite3.OperationalError: unable to open database file
[2023-04-13T11:35:28.019+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=create_table, execution_date=20230413T113526, start_date=20230413T113527, end_date=20230413T113528
[2023-04-13T11:35:28.030+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 82 for task create_table (unable to open database file; 3150)
[2023-04-13T11:35:28.060+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T11:35:28.090+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
