[2023-04-13T11:32:53.465+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.inject_data manual__2023-04-13T11:32:46.262170+00:00 [queued]>
[2023-04-13T11:32:53.476+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.inject_data manual__2023-04-13T11:32:46.262170+00:00 [queued]>
[2023-04-13T11:32:53.478+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T11:32:53.479+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T11:32:53.481+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T11:32:53.495+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): inject_data> on 2023-04-13 11:32:46.262170+00:00
[2023-04-13T11:32:53.501+0000] {standard_task_runner.py:55} INFO - Started process 3100 to run task
[2023-04-13T11:32:53.506+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'inject_data', 'manual__2023-04-13T11:32:46.262170+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpul58_ff1']
[2023-04-13T11:32:53.508+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask inject_data
[2023-04-13T11:32:53.595+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.inject_data manual__2023-04-13T11:32:46.262170+00:00 [running]> on host 0607b07c4f39
[2023-04-13T11:32:53.696+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=inject_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T11:32:46.262170+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T11:32:46.262170+00:00
[2023-04-13T11:32:53.700+0000] {sql.py:254} INFO - Executing: 
        INSERT INTO measures (timestamp, temp) VALUES
        (1681385281,
        286.84);
        
[2023-04-13T11:32:53.712+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T11:32:53.914+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T11:32:53.921+0000] {sql.py:375} INFO - Running statement: 
        INSERT INTO measures (timestamp, temp) VALUES
        (1681385281,
        286.84);
        , parameters: None
[2023-04-13T11:32:53.925+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: no such table: measures
[2023-04-13T11:32:53.942+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=inject_data, execution_date=20230413T113246, start_date=20230413T113253, end_date=20230413T113253
[2023-04-13T11:32:53.957+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 81 for task inject_data (no such table: measures; 3100)
[2023-04-13T11:32:54.008+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T11:32:54.037+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
