[2023-04-14T15:33:25.654+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.choose_endpoint_Kharkiv scheduled__2023-04-14T14:00:00+00:00 [queued]>
[2023-04-14T15:33:25.700+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.choose_endpoint_Kharkiv scheduled__2023-04-14T14:00:00+00:00 [queued]>
[2023-04-14T15:33:25.703+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T15:33:25.706+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-14T15:33:25.708+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T15:33:25.756+0000] {taskinstance.py:1309} INFO - Executing <Task(BranchPythonOperator): choose_endpoint_Kharkiv> on 2023-04-14 14:00:00+00:00
[2023-04-14T15:33:25.766+0000] {standard_task_runner.py:55} INFO - Started process 14939 to run task
[2023-04-14T15:33:25.781+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'choose_endpoint_Kharkiv', 'scheduled__2023-04-14T14:00:00+00:00', '--job-id', '507', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp4ttlo3an']
[2023-04-14T15:33:25.783+0000] {standard_task_runner.py:83} INFO - Job 507: Subtask choose_endpoint_Kharkiv
[2023-04-14T15:33:26.073+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.choose_endpoint_Kharkiv scheduled__2023-04-14T14:00:00+00:00 [running]> on host ffea11fb791c
[2023-04-14T15:33:26.312+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=choose_endpoint_Kharkiv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T14:00:00+00:00
[2023-04-14T15:33:26.316+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 210, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: choosing_endpoint() missing 1 required positional argument: 'city'
[2023-04-14T15:33:26.355+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=choose_endpoint_Kharkiv, execution_date=20230414T140000, start_date=20230414T153325, end_date=20230414T153326
[2023-04-14T15:33:26.389+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 507 for task choose_endpoint_Kharkiv (choosing_endpoint() missing 1 required positional argument: 'city'; 14939)
[2023-04-14T15:33:26.437+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T15:33:26.581+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
