[2023-04-13T20:02:19.563+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.inject_data_Kharkiv manual__2023-04-13T20:02:05.426770+00:00 [queued]>
[2023-04-13T20:02:19.587+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.inject_data_Kharkiv manual__2023-04-13T20:02:05.426770+00:00 [queued]>
[2023-04-13T20:02:19.590+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:02:19.592+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T20:02:19.593+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:02:19.642+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): inject_data_Kharkiv> on 2023-04-13 20:02:05.426770+00:00
[2023-04-13T20:02:19.660+0000] {standard_task_runner.py:55} INFO - Started process 6235 to run task
[2023-04-13T20:02:19.678+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'inject_data_Kharkiv', 'manual__2023-04-13T20:02:05.426770+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpnpqe6dlb']
[2023-04-13T20:02:19.688+0000] {standard_task_runner.py:83} INFO - Job 249: Subtask inject_data_Kharkiv
[2023-04-13T20:02:19.847+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.inject_data_Kharkiv manual__2023-04-13T20:02:05.426770+00:00 [running]> on host ffea11fb791c
[2023-04-13T20:02:19.924+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'inject_data_Kharkiv', field 'sql'. Template: '\n            INSERT INTO measures_ext (timestamp, temp, humidity, cloudiness, wind_speed) VALUES\n            ({{ti.xcom_pull(task_ids=f\'transform_data_{city}\')[0]}},\n            {{ti.xcom_pull(task_ids=f\'transform_data_{city}\')[1]}},\n            {{ti.xcom_pull(task_ids=f\'transform_data_{city}\')[2]}},\n            "{{ti.xcom_pull(task_ids=f\'transform_data_{city}\')[3]}}",\n            {{ti.xcom_pull(task_ids=f\'transform_data_{city}\')[4]}});\n            '
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 3, in template
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'string'
[2023-04-13T20:02:19.928+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1383, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2123, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 661, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 3, in template
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'string'
[2023-04-13T20:02:19.946+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=inject_data_Kharkiv, execution_date=20230413T200205, start_date=20230413T200219, end_date=20230413T200219
[2023-04-13T20:02:19.978+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 249 for task inject_data_Kharkiv (expected token ',', got 'string'; 6235)
[2023-04-13T20:02:20.019+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T20:02:20.053+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
