[2023-04-13T11:49:03.415+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.retrieve_weather_data manual__2023-04-13T11:49:00.661005+00:00 [queued]>
[2023-04-13T11:49:03.425+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.retrieve_weather_data manual__2023-04-13T11:49:00.661005+00:00 [queued]>
[2023-04-13T11:49:03.426+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T11:49:03.427+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T11:49:03.428+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T11:49:03.440+0000] {taskinstance.py:1309} INFO - Executing <Task(SimpleHttpOperator): retrieve_weather_data> on 2023-04-13 11:49:00.661005+00:00
[2023-04-13T11:49:03.446+0000] {standard_task_runner.py:55} INFO - Started process 184 to run task
[2023-04-13T11:49:03.450+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'retrieve_weather_data', 'manual__2023-04-13T11:49:00.661005+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpdpmnm_zx']
[2023-04-13T11:49:03.452+0000] {standard_task_runner.py:83} INFO - Job 90: Subtask retrieve_weather_data
[2023-04-13T11:49:03.514+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.retrieve_weather_data manual__2023-04-13T11:49:00.661005+00:00 [running]> on host ffea11fb791c
[2023-04-13T11:49:03.544+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'retrieve_weather_data', field 'data'. Template: {'q': 'Lviv', 'appid': '{{ OPENWEATHER_API }}'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 665, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'OPENWEATHER_API' is undefined
[2023-04-13T11:49:03.548+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1383, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1502, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2123, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 665, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'OPENWEATHER_API' is undefined
[2023-04-13T11:49:03.558+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=retrieve_weather_data, execution_date=20230413T114900, start_date=20230413T114903, end_date=20230413T114903
[2023-04-13T11:49:03.568+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 90 for task retrieve_weather_data ('OPENWEATHER_API' is undefined; 184)
[2023-04-13T11:49:03.582+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T11:49:03.607+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
