[2023-04-12T05:47:05.461+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2023-04-12T05:47:03.710529+00:00 [queued]>
[2023-04-12T05:47:05.489+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.create_table manual__2023-04-12T05:47:03.710529+00:00 [queued]>
[2023-04-12T05:47:05.492+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T05:47:05.495+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-12T05:47:05.500+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T05:47:05.524+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-12 05:47:03.710529+00:00
[2023-04-12T05:47:05.532+0000] {standard_task_runner.py:55} INFO - Started process 941 to run task
[2023-04-12T05:47:05.540+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'create_table', 'manual__2023-04-12T05:47:03.710529+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpmdysuarn']
[2023-04-12T05:47:05.543+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask create_table
[2023-04-12T05:47:05.669+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.create_table manual__2023-04-12T05:47:03.710529+00:00 [running]> on host 0607b07c4f39
[2023-04-12T05:47:05.765+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T05:47:03.710529+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-12T05:47:03.710529+00:00
[2023-04-12T05:47:05.768+0000] {sql.py:254} INFO - Executing: CREATE TABLE IF NOT EXISTS ...
[2023-04-12T05:47:05.801+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgresql://nazar:1111@localhost:5432/***-pipelines` isn't defined
[2023-04-12T05:47:05.815+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=create_table, execution_date=20230412T054703, start_date=20230412T054705, end_date=20230412T054705
[2023-04-12T05:47:05.842+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task create_table (The conn_id `postgresql://nazar:1111@localhost:5432/***-pipelines` isn't defined; 941)
[2023-04-12T05:47:05.915+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T05:47:06.047+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
